(global-set-key (kbd "s-h") 'windmove-left)
(global-set-key (kbd "s-j") 'windmove-down)
(global-set-key (kbd "s-k") 'windmove-up)
(global-set-key (kbd "s-l") 'windmove-right)

(global-set-key (kbd "s-H")
                #'(lambda (n)
                    (interactive "p")
                    (if (window-in-direction 'left)
                        (enlarge-window-horizontally n)
                      (shrink-window-horizontally n))))
(global-set-key (kbd "s-J")
                #'(lambda (n)
                    (interactive "p")
                    (if (window-in-direction 'below)
                        (enlarge-window n)
                      (shrink-window n))))
(global-set-key (kbd "s-K")
                #'(lambda (n)
                    (interactive "p")
                    (if (window-in-direction 'above)
                        (enlarge-window n)
                      (shrink-window n))))
(global-set-key (kbd "s-L")
                #'(lambda (n)
                    (interactive "p")
                    (if (window-in-direction 'right)
                        (enlarge-window-horizontally n)
                      (shrink-window-horizontally n))))

(el-get-bundle! buffer-move
  (global-set-key (kbd "M-g h") 'buf-move-left)
  (global-set-key (kbd "M-g j") 'buf-move-down)
  (global-set-key (kbd "M-g k") 'buf-move-up)
  (global-set-key (kbd "M-g l") 'buf-move-right))
